name: e2e Tests

# Run this workflow every time a new commit pushed to your repository
on: [pull_request]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  e2e:
    # Name the Job
    name: e2e Testing
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install depdendencies
        run: cd first-bank-of-change && npm ci

      - name: Install Narwhal/NX
        run: cd first-bank-of-change && npm install -g nx

      - name: Run e2e Tests
        run: npm run e2e-headless
