name: e2e Tests

# Run this workflow every time a new commit pushed to your repository
on: [pull_request]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  e2e:
    # Name the Job
    name: e2e Testing
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install depdendencies
        run: cd contino && npm install

      - name: Install Narwhal/NX
        run: cd contino && npm install -g nx

      # - name: Setup Chrome
      #   uses: nanasess/setup-chromedriver@master
      #   with:
      #     # Optional: do not specify to match Chrome's version
      #     chromedriver-version: '88.0.4324.96'

      # - name: Start Chrome
      #   run: |
      #     export DISPLAY=:99
      #     chromedriver --url-base=/wd/hub &
      #     sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Run e2e Tests
        run: npm run e2e-headless
